// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/assets.dart';
import 'api/convert.dart';
import 'api/icon.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApplyIconItem dco_decode_apply_icon_item(dynamic raw);

  @protected
  ApplyIconPayload dco_decode_apply_icon_payload(dynamic raw);

  @protected
  ApplyIconResult dco_decode_apply_icon_result(dynamic raw);

  @protected
  ApplyPayload dco_decode_apply_payload(dynamic raw);

  @protected
  ApplyPayloadItem dco_decode_apply_payload_item(dynamic raw);

  @protected
  ApplyResult dco_decode_apply_result(dynamic raw);

  @protected
  ApplyResultItem dco_decode_apply_result_item(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApplyIconPayload dco_decode_box_autoadd_apply_icon_payload(dynamic raw);

  @protected
  ApplyPayload dco_decode_box_autoadd_apply_payload(dynamic raw);

  @protected
  ConvertPayload dco_decode_box_autoadd_convert_payload(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ConvertItem dco_decode_convert_item(dynamic raw);

  @protected
  ConvertPayload dco_decode_convert_payload(dynamic raw);

  @protected
  ConvertResult dco_decode_convert_result(dynamic raw);

  @protected
  DroppedImage dco_decode_dropped_image(dynamic raw);

  @protected
  IconInspectResult dco_decode_icon_inspect_result(dynamic raw);

  @protected
  IconTarget dco_decode_icon_target(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ApplyIconItem> dco_decode_list_apply_icon_item(dynamic raw);

  @protected
  List<ApplyPayloadItem> dco_decode_list_apply_payload_item(dynamic raw);

  @protected
  List<ApplyResultItem> dco_decode_list_apply_result_item(dynamic raw);

  @protected
  List<ConvertItem> dco_decode_list_convert_item(dynamic raw);

  @protected
  List<DroppedImage> dco_decode_list_dropped_image(dynamic raw);

  @protected
  List<IconTarget> dco_decode_list_icon_target(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SlotDefinition> dco_decode_list_slot_definition(dynamic raw);

  @protected
  List<SlotInspectInfo> dco_decode_list_slot_inspect_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ProjectInspectResult dco_decode_project_inspect_result(dynamic raw);

  @protected
  ResolveDropResult dco_decode_resolve_drop_result(dynamic raw);

  @protected
  SlotDefinition dco_decode_slot_definition(dynamic raw);

  @protected
  SlotInspectInfo dco_decode_slot_inspect_info(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApplyIconItem sse_decode_apply_icon_item(SseDeserializer deserializer);

  @protected
  ApplyIconPayload sse_decode_apply_icon_payload(SseDeserializer deserializer);

  @protected
  ApplyIconResult sse_decode_apply_icon_result(SseDeserializer deserializer);

  @protected
  ApplyPayload sse_decode_apply_payload(SseDeserializer deserializer);

  @protected
  ApplyPayloadItem sse_decode_apply_payload_item(SseDeserializer deserializer);

  @protected
  ApplyResult sse_decode_apply_result(SseDeserializer deserializer);

  @protected
  ApplyResultItem sse_decode_apply_result_item(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApplyIconPayload sse_decode_box_autoadd_apply_icon_payload(
    SseDeserializer deserializer,
  );

  @protected
  ApplyPayload sse_decode_box_autoadd_apply_payload(
    SseDeserializer deserializer,
  );

  @protected
  ConvertPayload sse_decode_box_autoadd_convert_payload(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ConvertItem sse_decode_convert_item(SseDeserializer deserializer);

  @protected
  ConvertPayload sse_decode_convert_payload(SseDeserializer deserializer);

  @protected
  ConvertResult sse_decode_convert_result(SseDeserializer deserializer);

  @protected
  DroppedImage sse_decode_dropped_image(SseDeserializer deserializer);

  @protected
  IconInspectResult sse_decode_icon_inspect_result(
    SseDeserializer deserializer,
  );

  @protected
  IconTarget sse_decode_icon_target(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ApplyIconItem> sse_decode_list_apply_icon_item(
    SseDeserializer deserializer,
  );

  @protected
  List<ApplyPayloadItem> sse_decode_list_apply_payload_item(
    SseDeserializer deserializer,
  );

  @protected
  List<ApplyResultItem> sse_decode_list_apply_result_item(
    SseDeserializer deserializer,
  );

  @protected
  List<ConvertItem> sse_decode_list_convert_item(SseDeserializer deserializer);

  @protected
  List<DroppedImage> sse_decode_list_dropped_image(
    SseDeserializer deserializer,
  );

  @protected
  List<IconTarget> sse_decode_list_icon_target(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SlotDefinition> sse_decode_list_slot_definition(
    SseDeserializer deserializer,
  );

  @protected
  List<SlotInspectInfo> sse_decode_list_slot_inspect_info(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ProjectInspectResult sse_decode_project_inspect_result(
    SseDeserializer deserializer,
  );

  @protected
  ResolveDropResult sse_decode_resolve_drop_result(
    SseDeserializer deserializer,
  );

  @protected
  SlotDefinition sse_decode_slot_definition(SseDeserializer deserializer);

  @protected
  SlotInspectInfo sse_decode_slot_inspect_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_apply_icon_item(ApplyIconItem self, SseSerializer serializer);

  @protected
  void sse_encode_apply_icon_payload(
    ApplyIconPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_apply_icon_result(
    ApplyIconResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_apply_payload(ApplyPayload self, SseSerializer serializer);

  @protected
  void sse_encode_apply_payload_item(
    ApplyPayloadItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_apply_result(ApplyResult self, SseSerializer serializer);

  @protected
  void sse_encode_apply_result_item(
    ApplyResultItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_apply_icon_payload(
    ApplyIconPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_apply_payload(
    ApplyPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_convert_payload(
    ConvertPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_convert_item(ConvertItem self, SseSerializer serializer);

  @protected
  void sse_encode_convert_payload(
    ConvertPayload self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_convert_result(ConvertResult self, SseSerializer serializer);

  @protected
  void sse_encode_dropped_image(DroppedImage self, SseSerializer serializer);

  @protected
  void sse_encode_icon_inspect_result(
    IconInspectResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_icon_target(IconTarget self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_apply_icon_item(
    List<ApplyIconItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_apply_payload_item(
    List<ApplyPayloadItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_apply_result_item(
    List<ApplyResultItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_convert_item(
    List<ConvertItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dropped_image(
    List<DroppedImage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_icon_target(
    List<IconTarget> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slot_definition(
    List<SlotDefinition> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_slot_inspect_info(
    List<SlotInspectInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_inspect_result(
    ProjectInspectResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resolve_drop_result(
    ResolveDropResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slot_definition(
    SlotDefinition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_slot_inspect_info(
    SlotInspectInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
