// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/assets.dart';
import 'api/convert.dart';
import 'api/icon.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1920044632;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'pictool_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ApplyResult> crateApiAssetsApplyAssets({
    required ApplyPayload payload,
  });

  Future<ApplyIconResult> crateApiIconApplyIcon({
    required ApplyIconPayload payload,
  });

  Future<List<SlotDefinition>> crateApiAssetsAssetSlots();

  Future<ConvertResult> crateApiConvertConvertImages({
    required ConvertPayload payload,
  });

  Future<void> crateApiInitApp();

  Future<IconInspectResult> crateApiIconInspectIcons({
    required String projectDir,
  });

  Future<ProjectInspectResult> crateApiAssetsInspectProject({
    required String projectDir,
  });

  Future<Uint8List?> crateApiAssetsReadLargePreview({required String target});

  Future<Uint8List?> crateApiAssetsReadPreview({required String target});

  Future<ResolveDropResult> crateApiAssetsResolveDrop({
    required List<String> paths,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ApplyResult> crateApiAssetsApplyAssets({
    required ApplyPayload payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_apply_payload(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_apply_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAssetsApplyAssetsConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsApplyAssetsConstMeta =>
      const TaskConstMeta(debugName: "apply_assets", argNames: ["payload"]);

  @override
  Future<ApplyIconResult> crateApiIconApplyIcon({
    required ApplyIconPayload payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_apply_icon_payload(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_apply_icon_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIconApplyIconConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIconApplyIconConstMeta =>
      const TaskConstMeta(debugName: "apply_icon", argNames: ["payload"]);

  @override
  Future<List<SlotDefinition>> crateApiAssetsAssetSlots() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_slot_definition,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAssetsAssetSlotsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsAssetSlotsConstMeta =>
      const TaskConstMeta(debugName: "asset_slots", argNames: []);

  @override
  Future<ConvertResult> crateApiConvertConvertImages({
    required ConvertPayload payload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_convert_payload(payload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_convert_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConvertConvertImagesConstMeta,
        argValues: [payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConvertConvertImagesConstMeta =>
      const TaskConstMeta(debugName: "convert_images", argNames: ["payload"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<IconInspectResult> crateApiIconInspectIcons({
    required String projectDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_icon_inspect_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIconInspectIconsConstMeta,
        argValues: [projectDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIconInspectIconsConstMeta =>
      const TaskConstMeta(debugName: "inspect_icons", argNames: ["projectDir"]);

  @override
  Future<ProjectInspectResult> crateApiAssetsInspectProject({
    required String projectDir,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(projectDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_inspect_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAssetsInspectProjectConstMeta,
        argValues: [projectDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsInspectProjectConstMeta =>
      const TaskConstMeta(
        debugName: "inspect_project",
        argNames: ["projectDir"],
      );

  @override
  Future<Uint8List?> crateApiAssetsReadLargePreview({required String target}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(target, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAssetsReadLargePreviewConstMeta,
        argValues: [target],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsReadLargePreviewConstMeta =>
      const TaskConstMeta(
        debugName: "read_large_preview",
        argNames: ["target"],
      );

  @override
  Future<Uint8List?> crateApiAssetsReadPreview({required String target}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(target, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAssetsReadPreviewConstMeta,
        argValues: [target],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsReadPreviewConstMeta =>
      const TaskConstMeta(debugName: "read_preview", argNames: ["target"]);

  @override
  Future<ResolveDropResult> crateApiAssetsResolveDrop({
    required List<String> paths,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(paths, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_resolve_drop_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAssetsResolveDropConstMeta,
        argValues: [paths],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAssetsResolveDropConstMeta =>
      const TaskConstMeta(debugName: "resolve_drop", argNames: ["paths"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApplyIconItem dco_decode_apply_icon_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ApplyIconItem(
      dirName: dco_decode_String(arr[0]),
      targetPath: dco_decode_String(arr[1]),
      width: dco_decode_opt_box_autoadd_u_32(arr[2]),
      height: dco_decode_opt_box_autoadd_u_32(arr[3]),
      ok: dco_decode_bool(arr[4]),
      message: dco_decode_String(arr[5]),
    );
  }

  @protected
  ApplyIconPayload dco_decode_apply_icon_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApplyIconPayload(
      projectDir: dco_decode_String(arr[0]),
      sourcePath: dco_decode_String(arr[1]),
    );
  }

  @protected
  ApplyIconResult dco_decode_apply_icon_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApplyIconResult(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      items: dco_decode_list_apply_icon_item(arr[2]),
    );
  }

  @protected
  ApplyPayload dco_decode_apply_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ApplyPayload(
      projectDir: dco_decode_String(arr[0]),
      backup: dco_decode_bool(arr[1]),
      keepExtension: dco_decode_bool(arr[2]),
      items: dco_decode_list_apply_payload_item(arr[3]),
    );
  }

  @protected
  ApplyPayloadItem dco_decode_apply_payload_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApplyPayloadItem(
      slot: dco_decode_String(arr[0]),
      sourcePath: dco_decode_String(arr[1]),
    );
  }

  @protected
  ApplyResult dco_decode_apply_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApplyResult(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      items: dco_decode_list_apply_result_item(arr[2]),
    );
  }

  @protected
  ApplyResultItem dco_decode_apply_result_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ApplyResultItem(
      slot: dco_decode_String(arr[0]),
      slotLabel: dco_decode_String(arr[1]),
      sourcePath: dco_decode_String(arr[2]),
      targetPath: dco_decode_String(arr[3]),
      ok: dco_decode_bool(arr[4]),
      message: dco_decode_String(arr[5]),
      backupPath: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ApplyIconPayload dco_decode_box_autoadd_apply_icon_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_apply_icon_payload(raw);
  }

  @protected
  ApplyPayload dco_decode_box_autoadd_apply_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_apply_payload(raw);
  }

  @protected
  ConvertPayload dco_decode_box_autoadd_convert_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_convert_payload(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  ConvertItem dco_decode_convert_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ConvertItem(
      sourcePath: dco_decode_String(arr[0]),
      targetPath: dco_decode_String(arr[1]),
      width: dco_decode_opt_box_autoadd_u_32(arr[2]),
      height: dco_decode_opt_box_autoadd_u_32(arr[3]),
      ok: dco_decode_bool(arr[4]),
      message: dco_decode_String(arr[5]),
    );
  }

  @protected
  ConvertPayload dco_decode_convert_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ConvertPayload(
      sourcePaths: dco_decode_list_String(arr[0]),
      format: dco_decode_String(arr[1]),
      width: dco_decode_opt_box_autoadd_u_32(arr[2]),
      height: dco_decode_opt_box_autoadd_u_32(arr[3]),
      deleteOriginal: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ConvertResult dco_decode_convert_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ConvertResult(
      success: dco_decode_bool(arr[0]),
      message: dco_decode_String(arr[1]),
      items: dco_decode_list_convert_item(arr[2]),
    );
  }

  @protected
  DroppedImage dco_decode_dropped_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DroppedImage(
      path: dco_decode_String(arr[0]),
      fileName: dco_decode_String(arr[1]),
      suggestedSlot: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  IconInspectResult dco_decode_icon_inspect_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return IconInspectResult(
      projectDir: dco_decode_String(arr[0]),
      exists: dco_decode_bool(arr[1]),
      iconRoot: dco_decode_String(arr[2]),
      rootOk: dco_decode_bool(arr[3]),
      message: dco_decode_String(arr[4]),
      targets: dco_decode_list_icon_target(arr[5]),
    );
  }

  @protected
  IconTarget dco_decode_icon_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return IconTarget(
      dirName: dco_decode_String(arr[0]),
      dirPath: dco_decode_String(arr[1]),
      existingPath: dco_decode_opt_String(arr[2]),
      width: dco_decode_opt_box_autoadd_u_32(arr[3]),
      height: dco_decode_opt_box_autoadd_u_32(arr[4]),
      preview: dco_decode_opt_list_prim_u_8_strict(arr[5]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ApplyIconItem> dco_decode_list_apply_icon_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_apply_icon_item).toList();
  }

  @protected
  List<ApplyPayloadItem> dco_decode_list_apply_payload_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_apply_payload_item).toList();
  }

  @protected
  List<ApplyResultItem> dco_decode_list_apply_result_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_apply_result_item).toList();
  }

  @protected
  List<ConvertItem> dco_decode_list_convert_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_convert_item).toList();
  }

  @protected
  List<DroppedImage> dco_decode_list_dropped_image(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dropped_image).toList();
  }

  @protected
  List<IconTarget> dco_decode_list_icon_target(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_icon_target).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SlotDefinition> dco_decode_list_slot_definition(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_slot_definition).toList();
  }

  @protected
  List<SlotInspectInfo> dco_decode_list_slot_inspect_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_slot_inspect_info).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  ProjectInspectResult dco_decode_project_inspect_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProjectInspectResult(
      projectDir: dco_decode_String(arr[0]),
      exists: dco_decode_bool(arr[1]),
      structureOk: dco_decode_bool(arr[2]),
      missingDirs: dco_decode_list_String(arr[3]),
      message: dco_decode_String(arr[4]),
      slots: dco_decode_list_slot_inspect_info(arr[5]),
    );
  }

  @protected
  ResolveDropResult dco_decode_resolve_drop_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ResolveDropResult(
      projectDir: dco_decode_opt_String(arr[0]),
      images: dco_decode_list_dropped_image(arr[1]),
    );
  }

  @protected
  SlotDefinition dco_decode_slot_definition(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return SlotDefinition(
      key: dco_decode_String(arr[0]),
      label: dco_decode_String(arr[1]),
      relativePath: dco_decode_String(arr[2]),
      fileName: dco_decode_String(arr[3]),
      relativeDir: dco_decode_String(arr[4]),
      description: dco_decode_String(arr[5]),
    );
  }

  @protected
  SlotInspectInfo dco_decode_slot_inspect_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SlotInspectInfo(
      slot: dco_decode_String(arr[0]),
      slotLabel: dco_decode_String(arr[1]),
      targetPath: dco_decode_String(arr[2]),
      existingPath: dco_decode_opt_String(arr[3]),
      exists: dco_decode_bool(arr[4]),
      size: dco_decode_opt_box_autoadd_u_64(arr[5]),
      preview: dco_decode_opt_list_prim_u_8_strict(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApplyIconItem sse_decode_apply_icon_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dirName = sse_decode_String(deserializer);
    var var_targetPath = sse_decode_String(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_ok = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ApplyIconItem(
      dirName: var_dirName,
      targetPath: var_targetPath,
      width: var_width,
      height: var_height,
      ok: var_ok,
      message: var_message,
    );
  }

  @protected
  ApplyIconPayload sse_decode_apply_icon_payload(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectDir = sse_decode_String(deserializer);
    var var_sourcePath = sse_decode_String(deserializer);
    return ApplyIconPayload(
      projectDir: var_projectDir,
      sourcePath: var_sourcePath,
    );
  }

  @protected
  ApplyIconResult sse_decode_apply_icon_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_items = sse_decode_list_apply_icon_item(deserializer);
    return ApplyIconResult(
      success: var_success,
      message: var_message,
      items: var_items,
    );
  }

  @protected
  ApplyPayload sse_decode_apply_payload(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectDir = sse_decode_String(deserializer);
    var var_backup = sse_decode_bool(deserializer);
    var var_keepExtension = sse_decode_bool(deserializer);
    var var_items = sse_decode_list_apply_payload_item(deserializer);
    return ApplyPayload(
      projectDir: var_projectDir,
      backup: var_backup,
      keepExtension: var_keepExtension,
      items: var_items,
    );
  }

  @protected
  ApplyPayloadItem sse_decode_apply_payload_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_slot = sse_decode_String(deserializer);
    var var_sourcePath = sse_decode_String(deserializer);
    return ApplyPayloadItem(slot: var_slot, sourcePath: var_sourcePath);
  }

  @protected
  ApplyResult sse_decode_apply_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_items = sse_decode_list_apply_result_item(deserializer);
    return ApplyResult(
      success: var_success,
      message: var_message,
      items: var_items,
    );
  }

  @protected
  ApplyResultItem sse_decode_apply_result_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_slot = sse_decode_String(deserializer);
    var var_slotLabel = sse_decode_String(deserializer);
    var var_sourcePath = sse_decode_String(deserializer);
    var var_targetPath = sse_decode_String(deserializer);
    var var_ok = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_backupPath = sse_decode_opt_String(deserializer);
    return ApplyResultItem(
      slot: var_slot,
      slotLabel: var_slotLabel,
      sourcePath: var_sourcePath,
      targetPath: var_targetPath,
      ok: var_ok,
      message: var_message,
      backupPath: var_backupPath,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ApplyIconPayload sse_decode_box_autoadd_apply_icon_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_apply_icon_payload(deserializer));
  }

  @protected
  ApplyPayload sse_decode_box_autoadd_apply_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_apply_payload(deserializer));
  }

  @protected
  ConvertPayload sse_decode_box_autoadd_convert_payload(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_convert_payload(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  ConvertItem sse_decode_convert_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_targetPath = sse_decode_String(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_ok = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ConvertItem(
      sourcePath: var_sourcePath,
      targetPath: var_targetPath,
      width: var_width,
      height: var_height,
      ok: var_ok,
      message: var_message,
    );
  }

  @protected
  ConvertPayload sse_decode_convert_payload(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePaths = sse_decode_list_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_deleteOriginal = sse_decode_bool(deserializer);
    return ConvertPayload(
      sourcePaths: var_sourcePaths,
      format: var_format,
      width: var_width,
      height: var_height,
      deleteOriginal: var_deleteOriginal,
    );
  }

  @protected
  ConvertResult sse_decode_convert_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_items = sse_decode_list_convert_item(deserializer);
    return ConvertResult(
      success: var_success,
      message: var_message,
      items: var_items,
    );
  }

  @protected
  DroppedImage sse_decode_dropped_image(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_suggestedSlot = sse_decode_opt_String(deserializer);
    return DroppedImage(
      path: var_path,
      fileName: var_fileName,
      suggestedSlot: var_suggestedSlot,
    );
  }

  @protected
  IconInspectResult sse_decode_icon_inspect_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectDir = sse_decode_String(deserializer);
    var var_exists = sse_decode_bool(deserializer);
    var var_iconRoot = sse_decode_String(deserializer);
    var var_rootOk = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_targets = sse_decode_list_icon_target(deserializer);
    return IconInspectResult(
      projectDir: var_projectDir,
      exists: var_exists,
      iconRoot: var_iconRoot,
      rootOk: var_rootOk,
      message: var_message,
      targets: var_targets,
    );
  }

  @protected
  IconTarget sse_decode_icon_target(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_dirName = sse_decode_String(deserializer);
    var var_dirPath = sse_decode_String(deserializer);
    var var_existingPath = sse_decode_opt_String(deserializer);
    var var_width = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_height = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_preview = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return IconTarget(
      dirName: var_dirName,
      dirPath: var_dirPath,
      existingPath: var_existingPath,
      width: var_width,
      height: var_height,
      preview: var_preview,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApplyIconItem> sse_decode_list_apply_icon_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApplyIconItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_apply_icon_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApplyPayloadItem> sse_decode_list_apply_payload_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApplyPayloadItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_apply_payload_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApplyResultItem> sse_decode_list_apply_result_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApplyResultItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_apply_result_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<ConvertItem> sse_decode_list_convert_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ConvertItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_convert_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<DroppedImage> sse_decode_list_dropped_image(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DroppedImage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dropped_image(deserializer));
    }
    return ans_;
  }

  @protected
  List<IconTarget> sse_decode_list_icon_target(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <IconTarget>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_icon_target(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SlotDefinition> sse_decode_list_slot_definition(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SlotDefinition>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_slot_definition(deserializer));
    }
    return ans_;
  }

  @protected
  List<SlotInspectInfo> sse_decode_list_slot_inspect_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SlotInspectInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_slot_inspect_info(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectInspectResult sse_decode_project_inspect_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectDir = sse_decode_String(deserializer);
    var var_exists = sse_decode_bool(deserializer);
    var var_structureOk = sse_decode_bool(deserializer);
    var var_missingDirs = sse_decode_list_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_slots = sse_decode_list_slot_inspect_info(deserializer);
    return ProjectInspectResult(
      projectDir: var_projectDir,
      exists: var_exists,
      structureOk: var_structureOk,
      missingDirs: var_missingDirs,
      message: var_message,
      slots: var_slots,
    );
  }

  @protected
  ResolveDropResult sse_decode_resolve_drop_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectDir = sse_decode_opt_String(deserializer);
    var var_images = sse_decode_list_dropped_image(deserializer);
    return ResolveDropResult(projectDir: var_projectDir, images: var_images);
  }

  @protected
  SlotDefinition sse_decode_slot_definition(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_label = sse_decode_String(deserializer);
    var var_relativePath = sse_decode_String(deserializer);
    var var_fileName = sse_decode_String(deserializer);
    var var_relativeDir = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return SlotDefinition(
      key: var_key,
      label: var_label,
      relativePath: var_relativePath,
      fileName: var_fileName,
      relativeDir: var_relativeDir,
      description: var_description,
    );
  }

  @protected
  SlotInspectInfo sse_decode_slot_inspect_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_slot = sse_decode_String(deserializer);
    var var_slotLabel = sse_decode_String(deserializer);
    var var_targetPath = sse_decode_String(deserializer);
    var var_existingPath = sse_decode_opt_String(deserializer);
    var var_exists = sse_decode_bool(deserializer);
    var var_size = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_preview = sse_decode_opt_list_prim_u_8_strict(deserializer);
    return SlotInspectInfo(
      slot: var_slot,
      slotLabel: var_slotLabel,
      targetPath: var_targetPath,
      existingPath: var_existingPath,
      exists: var_exists,
      size: var_size,
      preview: var_preview,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_apply_icon_item(
    ApplyIconItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dirName, serializer);
    sse_encode_String(self.targetPath, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_apply_icon_payload(
    ApplyIconPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectDir, serializer);
    sse_encode_String(self.sourcePath, serializer);
  }

  @protected
  void sse_encode_apply_icon_result(
    ApplyIconResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_apply_icon_item(self.items, serializer);
  }

  @protected
  void sse_encode_apply_payload(ApplyPayload self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectDir, serializer);
    sse_encode_bool(self.backup, serializer);
    sse_encode_bool(self.keepExtension, serializer);
    sse_encode_list_apply_payload_item(self.items, serializer);
  }

  @protected
  void sse_encode_apply_payload_item(
    ApplyPayloadItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.slot, serializer);
    sse_encode_String(self.sourcePath, serializer);
  }

  @protected
  void sse_encode_apply_result(ApplyResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_apply_result_item(self.items, serializer);
  }

  @protected
  void sse_encode_apply_result_item(
    ApplyResultItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.slot, serializer);
    sse_encode_String(self.slotLabel, serializer);
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.targetPath, serializer);
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.backupPath, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_apply_icon_payload(
    ApplyIconPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_apply_icon_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_apply_payload(
    ApplyPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_apply_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_convert_payload(
    ConvertPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_convert_payload(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_convert_item(ConvertItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.targetPath, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_bool(self.ok, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_convert_payload(
    ConvertPayload self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.sourcePaths, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_bool(self.deleteOriginal, serializer);
  }

  @protected
  void sse_encode_convert_result(ConvertResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_convert_item(self.items, serializer);
  }

  @protected
  void sse_encode_dropped_image(DroppedImage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_opt_String(self.suggestedSlot, serializer);
  }

  @protected
  void sse_encode_icon_inspect_result(
    IconInspectResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectDir, serializer);
    sse_encode_bool(self.exists, serializer);
    sse_encode_String(self.iconRoot, serializer);
    sse_encode_bool(self.rootOk, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_icon_target(self.targets, serializer);
  }

  @protected
  void sse_encode_icon_target(IconTarget self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.dirName, serializer);
    sse_encode_String(self.dirPath, serializer);
    sse_encode_opt_String(self.existingPath, serializer);
    sse_encode_opt_box_autoadd_u_32(self.width, serializer);
    sse_encode_opt_box_autoadd_u_32(self.height, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.preview, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_apply_icon_item(
    List<ApplyIconItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_apply_icon_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_apply_payload_item(
    List<ApplyPayloadItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_apply_payload_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_apply_result_item(
    List<ApplyResultItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_apply_result_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_convert_item(
    List<ConvertItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_convert_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dropped_image(
    List<DroppedImage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dropped_image(item, serializer);
    }
  }

  @protected
  void sse_encode_list_icon_target(
    List<IconTarget> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_icon_target(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_slot_definition(
    List<SlotDefinition> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_slot_definition(item, serializer);
    }
  }

  @protected
  void sse_encode_list_slot_inspect_info(
    List<SlotInspectInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_slot_inspect_info(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_project_inspect_result(
    ProjectInspectResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectDir, serializer);
    sse_encode_bool(self.exists, serializer);
    sse_encode_bool(self.structureOk, serializer);
    sse_encode_list_String(self.missingDirs, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_slot_inspect_info(self.slots, serializer);
  }

  @protected
  void sse_encode_resolve_drop_result(
    ResolveDropResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.projectDir, serializer);
    sse_encode_list_dropped_image(self.images, serializer);
  }

  @protected
  void sse_encode_slot_definition(
    SlotDefinition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.relativePath, serializer);
    sse_encode_String(self.fileName, serializer);
    sse_encode_String(self.relativeDir, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_slot_inspect_info(
    SlotInspectInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.slot, serializer);
    sse_encode_String(self.slotLabel, serializer);
    sse_encode_String(self.targetPath, serializer);
    sse_encode_opt_String(self.existingPath, serializer);
    sse_encode_bool(self.exists, serializer);
    sse_encode_opt_box_autoadd_u_64(self.size, serializer);
    sse_encode_opt_list_prim_u_8_strict(self.preview, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
