// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_single`, `build_scaled`, `build_slot_inspect`, `exists`, `guess_format`, `looks_like_project_root`, `match_slot_file`, `remove_same_name_files`, `scan_images`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AssetSlot`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `base_name_of`, `ext_name_of`, `find_existing_file`, `get_slot`, `guess_slot`, `is_directory`, `is_file`, `is_image_file_name`, `open_image`, `to_absolute`

/// 读取图片为可直接渲染的字节流（缩略图）。
///
/// 大图直接回传原图会产生几 MB 的数据，桥接序列化与前端解码都会明显卡顿，
/// 因此这里统一缩放到 [`PREVIEW_MAX_EDGE`] 之内再编码。
Future<Uint8List?> readPreview({required String target}) =>
    RustLib.instance.api.crateApiAssetsReadPreview(target: target);

/// 读取放大查看用的较大预览。
///
/// 卡片上的缩略图只有 320px，放大后必然发虚；这里单独给一份最长边
/// [`LARGE_PREVIEW_MAX_EDGE`] 的版本，清晰度够用且体积可控。
Future<Uint8List?> readLargePreview({required String target}) =>
    RustLib.instance.api.crateApiAssetsReadLargePreview(target: target);

/// 三个素材槽位的界面定义
Future<List<SlotDefinition>> assetSlots() =>
    RustLib.instance.api.crateApiAssetsAssetSlots();

/// 扫描项目目录，返回三个槽位当前的状态与预览
Future<ProjectInspectResult> inspectProject({required String projectDir}) =>
    RustLib.instance.api.crateApiAssetsInspectProject(projectDir: projectDir);

/// 解析拖放进来的路径（可能是图片文件，也可能是文件夹）
Future<ResolveDropResult> resolveDrop({required List<String> paths}) =>
    RustLib.instance.api.crateApiAssetsResolveDrop(paths: paths);

/// 执行替换：按工程要求的名字写入目标位置
Future<ApplyResult> applyAssets({required ApplyPayload payload}) =>
    RustLib.instance.api.crateApiAssetsApplyAssets(payload: payload);

class ApplyPayload {
  final String projectDir;

  /// 替换前备份原文件（备份为 *.bak）
  final bool backup;

  /// 目标文件是否保留源图片扩展名（默认按工程要求不带扩展名）
  final bool keepExtension;
  final List<ApplyPayloadItem> items;

  const ApplyPayload({
    required this.projectDir,
    required this.backup,
    required this.keepExtension,
    required this.items,
  });

  @override
  int get hashCode =>
      projectDir.hashCode ^
      backup.hashCode ^
      keepExtension.hashCode ^
      items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyPayload &&
          runtimeType == other.runtimeType &&
          projectDir == other.projectDir &&
          backup == other.backup &&
          keepExtension == other.keepExtension &&
          items == other.items;
}

class ApplyPayloadItem {
  final String slot;
  final String sourcePath;

  const ApplyPayloadItem({required this.slot, required this.sourcePath});

  @override
  int get hashCode => slot.hashCode ^ sourcePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyPayloadItem &&
          runtimeType == other.runtimeType &&
          slot == other.slot &&
          sourcePath == other.sourcePath;
}

class ApplyResult {
  final bool success;
  final String message;
  final List<ApplyResultItem> items;

  const ApplyResult({
    required this.success,
    required this.message,
    required this.items,
  });

  @override
  int get hashCode => success.hashCode ^ message.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message &&
          items == other.items;
}

class ApplyResultItem {
  final String slot;
  final String slotLabel;
  final String sourcePath;

  /// 实际写入的目标文件路径
  final String targetPath;
  final bool ok;
  final String message;

  /// 备份文件路径
  final String? backupPath;

  const ApplyResultItem({
    required this.slot,
    required this.slotLabel,
    required this.sourcePath,
    required this.targetPath,
    required this.ok,
    required this.message,
    this.backupPath,
  });

  @override
  int get hashCode =>
      slot.hashCode ^
      slotLabel.hashCode ^
      sourcePath.hashCode ^
      targetPath.hashCode ^
      ok.hashCode ^
      message.hashCode ^
      backupPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyResultItem &&
          runtimeType == other.runtimeType &&
          slot == other.slot &&
          slotLabel == other.slotLabel &&
          sourcePath == other.sourcePath &&
          targetPath == other.targetPath &&
          ok == other.ok &&
          message == other.message &&
          backupPath == other.backupPath;
}

/// 拖放解析后的图片项
class DroppedImage {
  final String path;
  final String fileName;

  /// 根据文件名猜测应归属的槽位
  final String? suggestedSlot;

  const DroppedImage({
    required this.path,
    required this.fileName,
    this.suggestedSlot,
  });

  @override
  int get hashCode =>
      path.hashCode ^ fileName.hashCode ^ suggestedSlot.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DroppedImage &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          fileName == other.fileName &&
          suggestedSlot == other.suggestedSlot;
}

/// 扫描项目目录的结果
class ProjectInspectResult {
  final String projectDir;

  /// 目录是否存在
  final bool exists;

  /// 是否具备 src/main/assets 标准结构
  final bool structureOk;

  /// 缺失的目录（相对项目根目录）
  final List<String> missingDirs;

  /// 错误提示
  final String message;
  final List<SlotInspectInfo> slots;

  const ProjectInspectResult({
    required this.projectDir,
    required this.exists,
    required this.structureOk,
    required this.missingDirs,
    required this.message,
    required this.slots,
  });

  @override
  int get hashCode =>
      projectDir.hashCode ^
      exists.hashCode ^
      structureOk.hashCode ^
      missingDirs.hashCode ^
      message.hashCode ^
      slots.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectInspectResult &&
          runtimeType == other.runtimeType &&
          projectDir == other.projectDir &&
          exists == other.exists &&
          structureOk == other.structureOk &&
          missingDirs == other.missingDirs &&
          message == other.message &&
          slots == other.slots;
}

/// 拖放内容解析结果
class ResolveDropResult {
  /// 拖入的内容中识别出的项目根目录
  final String? projectDir;
  final List<DroppedImage> images;

  const ResolveDropResult({this.projectDir, required this.images});

  @override
  int get hashCode => projectDir.hashCode ^ images.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResolveDropResult &&
          runtimeType == other.runtimeType &&
          projectDir == other.projectDir &&
          images == other.images;
}

/// 一个槽位的界面定义（给前端渲染用）
class SlotDefinition {
  final String key;
  final String label;
  final String relativePath;
  final String fileName;
  final String relativeDir;
  final String description;

  const SlotDefinition({
    required this.key,
    required this.label,
    required this.relativePath,
    required this.fileName,
    required this.relativeDir,
    required this.description,
  });

  @override
  int get hashCode =>
      key.hashCode ^
      label.hashCode ^
      relativePath.hashCode ^
      fileName.hashCode ^
      relativeDir.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlotDefinition &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          label == other.label &&
          relativePath == other.relativePath &&
          fileName == other.fileName &&
          relativeDir == other.relativeDir &&
          description == other.description;
}

/// 项目中某个槽位当前的状态
class SlotInspectInfo {
  final String slot;

  /// 槽位显示名
  final String slotLabel;

  /// 期望的目标路径（不带扩展名）
  final String targetPath;

  /// 实际存在的文件路径（可能带扩展名），不存在为 None
  final String? existingPath;
  final bool exists;

  /// 现有文件字节数
  final BigInt? size;

  /// 现有图片的缩略图字节（PNG / JPEG），过大或不存在为 None
  final Uint8List? preview;

  const SlotInspectInfo({
    required this.slot,
    required this.slotLabel,
    required this.targetPath,
    this.existingPath,
    required this.exists,
    this.size,
    this.preview,
  });

  @override
  int get hashCode =>
      slot.hashCode ^
      slotLabel.hashCode ^
      targetPath.hashCode ^
      existingPath.hashCode ^
      exists.hashCode ^
      size.hashCode ^
      preview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlotInspectInfo &&
          runtimeType == other.runtimeType &&
          slot == other.slot &&
          slotLabel == other.slotLabel &&
          targetPath == other.targetPath &&
          existingPath == other.existingPath &&
          exists == other.exists &&
          size == other.size &&
          preview == other.preview;
}
