// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert_single`, `format_of`, `invalid`, `save_as`, `target_size`, `with_extension`

/// 批量转换：输出到源文件同目录，文件名不变、只换扩展名
Future<ConvertResult> convertImages({required ConvertPayload payload}) =>
    RustLib.instance.api.crateApiConvertConvertImages(payload: payload);

class ConvertItem {
  final String sourcePath;
  final String targetPath;
  final int? width;
  final int? height;
  final bool ok;
  final String message;

  const ConvertItem({
    required this.sourcePath,
    required this.targetPath,
    this.width,
    this.height,
    required this.ok,
    required this.message,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      targetPath.hashCode ^
      width.hashCode ^
      height.hashCode ^
      ok.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvertItem &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          targetPath == other.targetPath &&
          width == other.width &&
          height == other.height &&
          ok == other.ok &&
          message == other.message;
}

class ConvertPayload {
  final List<String> sourcePaths;

  /// jpg | jpeg | png | webp | bmp
  final String format;

  /// 目标宽度，留空保持原尺寸
  final int? width;

  /// 目标高度，留空保持原尺寸
  final int? height;

  /// 转换成功后删除原文件
  final bool deleteOriginal;

  const ConvertPayload({
    required this.sourcePaths,
    required this.format,
    this.width,
    this.height,
    required this.deleteOriginal,
  });

  @override
  int get hashCode =>
      sourcePaths.hashCode ^
      format.hashCode ^
      width.hashCode ^
      height.hashCode ^
      deleteOriginal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvertPayload &&
          runtimeType == other.runtimeType &&
          sourcePaths == other.sourcePaths &&
          format == other.format &&
          width == other.width &&
          height == other.height &&
          deleteOriginal == other.deleteOriginal;
}

class ConvertResult {
  final bool success;
  final String message;
  final List<ConvertItem> items;

  const ConvertResult({
    required this.success,
    required this.message,
    required this.items,
  });

  @override
  int get hashCode => success.hashCode ^ message.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConvertResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message &&
          items == other.items;
}
