// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_icon_to_dir`, `collect_drawable_dirs`, `empty_inspect`, `find_icon_file`, `fit_into`, `icon_root_of`, `invalid`, `is_drawable_dir_name`, `read_icon_size`, `remove_icon_files`, `save_image`, `writable_ext`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `flatten_on_white`

/// 扫描 `src/main/res/drawable*` 下的 icon 现状
Future<IconInspectResult> inspectIcons({required String projectDir}) =>
    RustLib.instance.api.crateApiIconInspectIcons(projectDir: projectDir);

/// 把同一张源图按各 drawable 目录原有尺寸缩放后写入 `icon.<源扩展名>`
Future<ApplyIconResult> applyIcon({required ApplyIconPayload payload}) =>
    RustLib.instance.api.crateApiIconApplyIcon(payload: payload);

class ApplyIconItem {
  final String dirName;
  final String targetPath;
  final int? width;
  final int? height;
  final bool ok;
  final String message;

  const ApplyIconItem({
    required this.dirName,
    required this.targetPath,
    this.width,
    this.height,
    required this.ok,
    required this.message,
  });

  @override
  int get hashCode =>
      dirName.hashCode ^
      targetPath.hashCode ^
      width.hashCode ^
      height.hashCode ^
      ok.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyIconItem &&
          runtimeType == other.runtimeType &&
          dirName == other.dirName &&
          targetPath == other.targetPath &&
          width == other.width &&
          height == other.height &&
          ok == other.ok &&
          message == other.message;
}

class ApplyIconPayload {
  final String projectDir;
  final String sourcePath;

  const ApplyIconPayload({required this.projectDir, required this.sourcePath});

  @override
  int get hashCode => projectDir.hashCode ^ sourcePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyIconPayload &&
          runtimeType == other.runtimeType &&
          projectDir == other.projectDir &&
          sourcePath == other.sourcePath;
}

class ApplyIconResult {
  final bool success;
  final String message;
  final List<ApplyIconItem> items;

  const ApplyIconResult({
    required this.success,
    required this.message,
    required this.items,
  });

  @override
  int get hashCode => success.hashCode ^ message.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApplyIconResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          message == other.message &&
          items == other.items;
}

class IconInspectResult {
  final String projectDir;
  final bool exists;
  final String iconRoot;
  final bool rootOk;
  final String message;
  final List<IconTarget> targets;

  const IconInspectResult({
    required this.projectDir,
    required this.exists,
    required this.iconRoot,
    required this.rootOk,
    required this.message,
    required this.targets,
  });

  @override
  int get hashCode =>
      projectDir.hashCode ^
      exists.hashCode ^
      iconRoot.hashCode ^
      rootOk.hashCode ^
      message.hashCode ^
      targets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IconInspectResult &&
          runtimeType == other.runtimeType &&
          projectDir == other.projectDir &&
          exists == other.exists &&
          iconRoot == other.iconRoot &&
          rootOk == other.rootOk &&
          message == other.message &&
          targets == other.targets;
}

class IconTarget {
  final String dirName;
  final String dirPath;
  final String? existingPath;
  final int? width;
  final int? height;

  /// 现有 icon 的缩略图字节
  final Uint8List? preview;

  const IconTarget({
    required this.dirName,
    required this.dirPath,
    this.existingPath,
    this.width,
    this.height,
    this.preview,
  });

  @override
  int get hashCode =>
      dirName.hashCode ^
      dirPath.hashCode ^
      existingPath.hashCode ^
      width.hashCode ^
      height.hashCode ^
      preview.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IconTarget &&
          runtimeType == other.runtimeType &&
          dirName == other.dirName &&
          dirPath == other.dirPath &&
          existingPath == other.existingPath &&
          width == other.width &&
          height == other.height &&
          preview == other.preview;
}
